# Generated by Django 3.2.20 on 2023-07-07 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField()),
                ('WRITER', models.IntegerField()),
                ('APPROVER', models.IntegerField()),
                ('DELETED', models.IntegerField()),
                ('STATUS', models.IntegerField()),
                ('TITLE', models.CharField(max_length=100)),
                ('CONTENT', models.TextField()),
                ('SCORE', models.IntegerField()),
                ('CREATED', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('EMAIL', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=10)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('CREATED', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
