# Generated by Django 3.2.20 on 2023-07-09 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField()),
                ('CTYPE', models.CharField(max_length=10)),
                ('WRITER', models.IntegerField()),
                ('APPROVER', models.IntegerField()),
                ('DELETED', models.IntegerField()),
                ('STATUS', models.IntegerField()),
                ('CONTENT', models.TextField()),
                ('NUM_LIKE', models.IntegerField(default=0)),
                ('NUM_SAVED', models.IntegerField(default=0)),
                ('NUM_SHARE', models.IntegerField(default=0)),
                ('CREATED', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
