# Generated by Django 3.2.20 on 2023-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230709_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField()),
                ('STATUS', models.IntegerField(default=0)),
                ('NAME', models.CharField(max_length=30)),
                ('CONTENT', models.TextField(blank=True)),
                ('REVIEWS', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='FOLLOWING',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LIKES',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='SAVED',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='CONTENT',
            field=models.TextField(blank=True),
        ),
    ]
