# Generated by Django 4.2.3 on 2023-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230711_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='content',
            name='GPT',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='CID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
